### ISSUE TITLE
Vec2Word

### ISSUE THREAD

**Issue by silentrob** [Planeshifter/node-word2vec#1]
Given the example provided.
vector('king') - vector('man') + vector('woman')  

It would be nice to be able to pass in the raw vector and get the word.

**Comment by Planeshifter** [comment]
I have added functions `getNearestWord`  and `getNearestWords` which allow to retrieve the word(s) closest to the supplied input vector. Additionally, there are now functions to  perform addition and subtraction of word vectors. Pushed a new version of the package, 0.6.0, to npm. Hope you find the additions useful.

**Comment by silentrob** [comment]
Thanks so much! Looking forward to playing with it!

**Comment by Planeshifter** [comment]
Let me know if you run into any problems. Best, Philipp

**Comment by soumyadeep-kundu** [comment]
Can anyone tell me how to get words from vectors i.e. vec2word?

**Comment by ishitaarora05** [comment]
Hi Philipp!
I am trying to implement vec2word but facing issues with the code. 

Do you have any code with you that I can implement or if I can share my code with you? Please let me know. Thank you
