### ISSUE TITLE
.mostSimilar() returns array of undefined words for an out-of-dictionary word

### ISSUE THREAD

**Issue by josephrocca** [Planeshifter/node-word2vec#10]
As the title says, `.mostSimilar()` returns array of objects with `word = undefined` and `dist = -1` for an out-of-dictionary word. The array is as long as the number of entries requested in the second argument of `mostSimilar`. I would expect it to return an empty array or null if the word is not found in the dictionary.

Cheers

**Comment by Planeshifter** [comment]
Thanks for this suggestion! I changed the functionality of the function such that it now returns `null` if all phrase words are out-of-dictionary.

**Comment by josephrocca** [comment]
Thanks!
