### ISSUE TITLE
.similarity(term1, term2) returns null for two identical terms instead of 1

### ISSUE THREAD

**Issue by suissemaxx** [Planeshifter/node-word2vec#13]
Thank you very much for the node-port of w2v. Very helpful and very much appreciated!

A minor quirk I just stumbled upon: The similarity between two equal terms results in null rather than 1. I checked the same model in gensim and there I get a similarity of 1.0 as expected. 

Why is that?

**Comment by Planeshifter** [comment]
Thank you for filing this issue! I changed the code to handle this case and have pushed a fix to GitHub and npm.
