### ISSUE TITLE
'make' is not recognized as an internal or external command, in windows 64 bit

### ISSUE THREAD

**Issue by lokesh1233** [Planeshifter/node-word2vec#15]
> make --directory=src

'make' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "F:\\studies\\node\\node.exe" "F:\\studies\\node\\node_modules\\npm\\bin\\npm-cli.js" "install" "word2vec"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! word2vec@1.1.1 postinstall: `make --directory=src`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the word2vec@1.1.1 postinstall script 'make --directory=src'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the word2vec package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     make --directory=src
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs word2vec
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls word2vec
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\git repository\npm-debug.log

**Comment by Planeshifter** [comment]
Unfortunately, `word2vec` is only supported for UNIX operating systems, and you are likely to have a hard time getting it to work on Windows.
