### ISSUE TITLE
npm Test problem

### ISSUE THREAD

**Issue by dieboldfr** [Planeshifter/node-word2vec#3]
Hello,
It seems there are some files missing for the "npm test":
  1) word2phrase can be called successfully:
     Uncaught AssertionError: expected false to be true

Do you continue this project?

Thanks,
Thomas

**Comment by dieboldfr** [comment]
Same thing in the examples directory

**Comment by Planeshifter** [comment]
Hey Thomas,
did you by chance clone the Github repo instead of installing from `npm`? I just realized that I did not commit two files which are required to run the tests. Please pull the recent changes and let me know if the problem persists.
Best,
Philipp

**Comment by dieboldfr** [comment]
Thank you for your update.
But It seems I have always a problem with the test word2phase

Which nodejs version do you use? I tried to check with 010.28 and the last one 0.12. on windows / ubuntu env

  word2phrase
    ✓ is a callable function
    1) can be called successfully


  14 passing (15s)
  1 failing

  1) word2phrase can be called successfully:
     Error: timeout of 15000ms exceeded. Ensure the done() callback is being called in this test.
  
On windows:
I have these problem
child_process: customFds option is deprecated, use stdio instead.

  ................

  14 passing (198ms)
  2 failing

  1) loadModel successfully loads a model file:
     Uncaught TypeError: undefined is not a function
      at readOne (C:\Users\thomas\Documents\playdocker\cable\github\tmp\node-wor
d2vec\lib\model.js:433:55)
      at callback (C:\Users\thomas\AppData\Roaming\npm\node_modules\mocha\node_m
odules\glob\node_modules\graceful-fs\polyfills.js:207:17)
      at FSReqWrap.wrapper [as oncomplete] (fs.js:529:17)

  2) word2phrase can be called successfully:
     Uncaught Error: spawn ./word2phrase ENOENT
      at exports._errnoException (util.js:746:11)
      at Process.ChildProcess._handle.onexit (child_process.js:1046:32)
      at child_process.js:1137:20
      at process._tickCallback (node.js:355:11)

Maybe a problem with the c integration on nodejs. Let me know.
Thanks again

**Comment by Planeshifter** [comment]
You might need to recompile the C source files. Could you please follow the following steps and let me know if the problem persists.

Clone the git repository with the command

``` bash
$ git clone https://github.com/Planeshifter/node-word2vec.git
```

Change into the project directory and compile the C source files via

``` bash
$ cd node-word2vec
$ make --directory=src
```

Run the tests via 

``` bash
npm test 
```

**Comment by dieboldfr** [comment]
Thx very much !
