### ISSUE TITLE
In v1.0,  the callback to loadModel doesn't get fired and no error messages are thrown

### ISSUE THREAD

**Issue by josephrocca** [Planeshifter/node-word2vec#9]
As the title says, my loadModel callback never gets called and no error messages get thrown.

I had to copy model.js from 0.9.2 and make the changes mentioned in #8 to get it working again.

Cheers

**Comment by Planeshifter** [comment]
Hi there, started working through your filed issues. I have incorporated the changed suggested in #8 
and pushed a new version to GitHub. Can you install directly from GitHub (`npm install https://github.com/Planeshifter/node-word2vec.git`) and verify that the code now works for your use case? If so, I will land a new version on npm soon. Thanks!

**Comment by josephrocca** [comment]
I had no particular/distinctive use case, it was just not throwing the callback as expected (and as occured in the previous version). So if that's working now, that's great - thanks. If I get a chance to test it tomorrow I'll post my result here
